name: WpmFlow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}



      - name: Append current date to env
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Docker build
        run: |
          docker build \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg RUN_NUMBER=${{ github.run_number }} \
            -t myregistry.azurecr.io/myapp:${{ github.run_number }} .

      - name: Docker push
        run: docker push myregistry.azurecr.io/myapp:${{ github.run_number }}
